### ISSUE TITLE
大佬，这个组件能够解决我迫在眉睫的部分问题！请问支持获取到所有的输入事件吗？

### ISSUE THREAD

**Issue by zjjjjjjjjjjd** [Yufeikang/react-native-key-event#1]
因为我是在手持设备上开发，按键的事件可以解决物理键盘的响应，但是当扫描条形码时获取的输入值都是为空，大佬知道怎么弄吗？

**Comment by yufeikang** [comment]
这个项目当时就是为了扫码器写的. 你先确认2步

1.选中某个应用的输入框, 如浏览器地址栏用扫码器扫码看是否输出
2.如果可以输出, 输出event对象看是否有内容

**Comment by zjjjjjjjjjjd** [comment]
是的，原生的输入框内是可以输入的，打印出来的是这个
![Snipaste_2019-03-29_16-08-49](https://user-images.githubusercontent.com/32830366/55218413-0280f800-523d-11e9-9e78-45619dbb35de.png)

Number和displayLabel都是空的，会不会是类型转换的问题？

**Comment by zjjjjjjjjjjd** [comment]
排查了一天，我不是很懂安卓，我发现这种char转换之后似乎会乱码，不知道是不是我手持设备的原因，在输入框输入的时候是没有问题的
![Snipaste_2019-03-29_18-42-09](https://user-images.githubusercontent.com/32830366/55227493-9610f380-5252-11e9-854e-3126ca27095a.png)
![Snipaste_2019-03-29_18-42-23](https://user-images.githubusercontent.com/32830366/55227495-9610f380-5252-11e9-91d1-e38c32090b17.png)

**Comment by yufeikang** [comment]
@zjjjjjjjjjjd 
把输入法切换到英文状态再试
